 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mixes", type: :request do
  # Mix. As you add validations to Mix, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Mix.create! valid_attributes
      get mixes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mix = Mix.create! valid_attributes
      get mix_url(mix)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mix_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mix = Mix.create! valid_attributes
      get edit_mix_url(mix)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Mix" do
        expect {
          post mixes_url, params: { mix: valid_attributes }
        }.to change(Mix, :count).by(1)
      end

      it "redirects to the created mix" do
        post mixes_url, params: { mix: valid_attributes }
        expect(response).to redirect_to(mix_url(Mix.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Mix" do
        expect {
          post mixes_url, params: { mix: invalid_attributes }
        }.to change(Mix, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mixes_url, params: { mix: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mix" do
        mix = Mix.create! valid_attributes
        patch mix_url(mix), params: { mix: new_attributes }
        mix.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mix" do
        mix = Mix.create! valid_attributes
        patch mix_url(mix), params: { mix: new_attributes }
        mix.reload
        expect(response).to redirect_to(mix_url(mix))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mix = Mix.create! valid_attributes
        patch mix_url(mix), params: { mix: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mix" do
      mix = Mix.create! valid_attributes
      expect {
        delete mix_url(mix)
      }.to change(Mix, :count).by(-1)
    end

    it "redirects to the mixes list" do
      mix = Mix.create! valid_attributes
      delete mix_url(mix)
      expect(response).to redirect_to(mixes_url)
    end
  end
end
